[FORMAT]   [ID]            [TIME]              [MODULE]   [MESSAGE]
[32m[INFO]     [35mNone            [34m28/09/2024 15:31:44 [33m[DB]       [0mConnecting to db . . .
[32m[INFO]     [35mNone            [34m28/09/2024 15:31:44 [33m[DB]       [0mCreate a course . . .
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCritical error: "cannot import name 'dict_name_lessons' from 'utils' (/usr/local/Project/Python/TG_bot_Nion/utils.py)"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCommand: "import main  # noqa: F401"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mLine: 8
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mFile: "/usr/local/Project/Python/TG_bot_Nion/start.py"

[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCritical error: "cannot import name 'dict_name_lessons' from 'utils' (/usr/local/Project/Python/TG_bot_Nion/utils.py)"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCommand: "File "/usr/local/Project/Python/TG_bot_Nion/main.py", line 17, in <module>"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mLine: ^^^^^^^^^^^
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mFile: ^^^^^^^^^^^

[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCritical error: "cannot import name 'dict_name_lessons' from 'utils' (/usr/local/Project/Python/TG_bot_Nion/utils.py)"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCommand: "File "/usr/local/Project/Python/TG_bot_Nion/kb.py", line 7, in <module>"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mLine: import kb
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mFile: import kb

[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCritical error: "cannot import name 'dict_name_lessons' from 'utils' (/usr/local/Project/Python/TG_bot_Nion/utils.py)"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mCommand: "ImportError: cannot import name 'dict_name_lessons' from 'utils' (/usr/local/Project/Python/TG_bot_Nion/utils.py)"
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mLine: from utils import dict_name_lessons, num_lessons, check_for_admin, format_date
[31m[CERROR]   [35mNone            [34m28/09/2024 15:31:44 [31m[START]    [0mFile: from utils import dict_name_lessons

